language: c++

cache:
  ccache: true

addons:
  apt:
    update: true
    packages:
      - clang
      - clang-format
      - llvm
      - llvm-dev
      - lcov
      - ruby
      - gcc-12
      - g++-12

env:
  global:
    - CMAKE_C_COMPILER_LAUNCHER=ccache
    - CMAKE_CXX_COMPILER_LAUNCHER=ccache

jobs:
  include:
    - name: "Static Analysis"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSTATIC_ANALYSIS=ON .
      script:
        - cmake --build . --config Debug --parallel 3

    - name: "Sanitizer"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - mkdir build-address
        - pushd build-address
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZER=Address ..
        - cmake --build . --config Debug --parallel 3
        - popd
        - mkdir build-stack
        - pushd build-stack
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZER=Stack ..
        - cmake --build . --config Debug --parallel 3
        - popd
        - mkdir build-thread
        - pushd build-thread
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZER=Thread ..
        - cmake --build . --config Debug --parallel 3
        - popd
      script:
        - pushd build-address/tests
        - ctest -j1 --output-on-failure
        - popd
        - pushd build-stack/tests
        - ctest -j1 --output-on-failure
        - popd
        - pushd build-thread/tests
        - ctest -j1 --output-on-failure

    - name: "Coverage"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      install:
        - sudo gem install coveralls-lcov
      before_script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON ..
      script:
        - cmake --build . --config Debug --parallel 3 --target coverage
      after_success:
        - coveralls-lcov --repo-token $COVERALLS_REPO_TOKEN --service-name travis-pro --service-job-id $TRAVIS_JOB_ID ./coverage.info

    - name: "GCC Unit Tests"
      os: linux
      dist: jammy
      env:
        - CC=gcc-12
        - CXX=g++-12
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
        - cmake --build . --config Release --parallel 3
      script:
        - cd tests
        - ctest -j3 --output-on-failure

    - name: "Clang Unit Tests and Formatting"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
        - cmake --build . --config Release --parallel 3
      script:
        - cmake --build . --config Release --parallel 3 --target format.check
        - cd tests
        - ctest -j3 --output-on-failure

notifications:
  slack:
    secure: XI5HQX1L7biQ/djmHbFgnzrHPYSWRqD1PnMykTYe0lCQhQYeVVIMReiPkzLCzvd/+SXawRTRmCRZqL+j+bf56HuzTXYnXouXRW+Wat1+Gvee4fhf5V9MsMlytxJ+H90mbQ8P9XSz8nrRnNHTkxOYudZX6lZ3zvZxLucbvLFYx9y/bEPbnNd1qv9kgulv9QhvgrVJ14CZEhNRm+9HBXg02YB0Wc/BmDIc5TMci5nTdcpbBuwZ7lYe2LdL4LQpHY5R85bn4kTrqXtsmG6iXpOH0JZHOk+OM3rJTL7hf1Z09PjsXxdb1z/yhkws7kRlBKCB5s7d17kD8qkCVD2ywZKMh/lSIG4Gm7oDv7P2RY6+7tGGPVyImKxtyhKHpPNnx4T2Y1mwIbAiGRA5DkmfoTevx5ygcXoU35P08qvjaM/1m0fjYcO2Ud2TXOzNJ7Y1XOdMS11Y9PRmnnPOpy15D5kwhNPCed+nZj4G04r8UTcbnOuZvknMTq+HgEWoI65t9iKbX81LirBAi+Tpi8MnMRi8Lm2jCoSrwHx0L1I+RfK3BXDvPjkWIlyn54EEoObguO4cqJ5tag2jrN5/QjWbmyXe+GwWT9+BCtaE+GrBiAp2c8jNc1o1SkzFfs1fH+d2v5+3iJvb3PoLYQa31Kkm0cRF1uNFYfqYy67u2aHagjHTBc0=
    on_success: never
